"""empty message

Revision ID: 037cec4e93da
Revises: 010b6ee92080
Create Date: 2016-08-18 22:16:36.960126

"""

# revision identifiers, used by Alembic.
revision = '037cec4e93da'
down_revision = '010b6ee92080'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
