"""empty message

Revision ID: 1a51edd57742
Revises: 1d2b6e7cf5ba
Create Date: 2016-08-21 08:34:45.847327

"""

# revision identifiers, used by Alembic.
revision = '1a51edd57742'
down_revision = '1d2b6e7cf5ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_data', sa.Column('player_id', sa.Integer(), nullable=True))
    op.drop_constraint('player_data_player_fkey', 'player_data', type_='foreignkey')
    op.create_foreign_key(None, 'player_data', 'player', ['player_id'], ['id'])
    op.drop_column('player_data', 'player')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_data', sa.Column('player', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'player_data', type_='foreignkey')
    op.create_foreign_key('player_data_player_fkey', 'player_data', 'player', ['player'], ['id'])
    op.drop_column('player_data', 'player_id')
    ### end Alembic commands ###
