"""empty message

Revision ID: 87aed14cd699
Revises: 1a51edd57742
Create Date: 2016-08-21 09:50:35.091406

"""

# revision identifiers, used by Alembic.
revision = '87aed14cd699'
down_revision = '1a51edd57742'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_data', sa.Column('game_id', sa.Integer(), nullable=True))
    op.drop_constraint('player_data_game_fkey', 'player_data', type_='foreignkey')
    op.create_foreign_key(None, 'player_data', 'game', ['game_id'], ['id'])
    op.drop_column('player_data', 'game')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_data', sa.Column('game', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'player_data', type_='foreignkey')
    op.create_foreign_key('player_data_game_fkey', 'player_data', 'game', ['game'], ['id'])
    op.drop_column('player_data', 'game_id')
    ### end Alembic commands ###
