"""empty message

Revision ID: 978ec019e504
Revises: None
Create Date: 2016-08-18 18:31:14.230668

"""

# revision identifiers, used by Alembic.
revision = '978ec019e504'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=120), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('opponent', sa.String(length=120), nullable=True),
    sa.Column('your_score', sa.Integer(), nullable=True),
    sa.Column('opponent_score', sa.Integer(), nullable=True),
    sa.Column('home', sa.Boolean(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('team', sa.String(length=120), nullable=True),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('ext_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PlayerData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('pass_attempts', sa.Integer(), nullable=True),
    sa.Column('pass_completions', sa.Integer(), nullable=True),
    sa.Column('pass_yards', sa.Integer(), nullable=True),
    sa.Column('pass_touchdowns', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('rush_attempts', sa.Integer(), nullable=True),
    sa.Column('rush_yards', sa.Integer(), nullable=True),
    sa.Column('rush_touchdowns', sa.Integer(), nullable=True),
    sa.Column('rec_yards', sa.Integer(), nullable=True),
    sa.Column('rec_touchdowns', sa.Integer(), nullable=True),
    sa.Column('receptions', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('predicted', sa.Integer(), nullable=True),
    sa.Column('extra_point_kick', sa.Integer(), nullable=True),
    sa.Column('three_point_kick', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['Game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['Player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PlayerData')
    op.drop_table('Player')
    op.drop_table('Game')
    op.drop_table('user')
    ### end Alembic commands ###
